version: 2
jobs:
  lint:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node-browsers
    steps:
      - checkout
      - run: gem install mdl && mdl .
workflows:
  version: 2
  just_lint:
    jobs:
      - lint